"""add user collections

Revision ID: 2e085eb11b68
Revises: 8123e8c1c487
Create Date: 2026-05-22 17:54:43.429351+00:00
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



revision: str = '2e085eb11b68'
down_revision: str | None = '8123e8c1c487'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('collection_name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('embedding_provider', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'collection_name', name='uq_user_collection_name')
    )
    op.create_index(op.f('ix_user_collections_collection_name'), 'user_collections', ['collection_name'], unique=False)
    op.create_index(op.f('ix_user_collections_id'), 'user_collections', ['id'], unique=False)
    op.create_index(op.f('ix_user_collections_session_id'), 'user_collections', ['session_id'], unique=False)
    op.create_index(op.f('ix_user_collections_user_id'), 'user_collections', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_collections_user_id'), table_name='user_collections')
    op.drop_index(op.f('ix_user_collections_session_id'), table_name='user_collections')
    op.drop_index(op.f('ix_user_collections_id'), table_name='user_collections')
    op.drop_index(op.f('ix_user_collections_collection_name'), table_name='user_collections')
    op.drop_table('user_collections')
    # ### end Alembic commands ###
